# Generated by Django 5.0.1 on 2025-08-14 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org_type', models.CharField(choices=[('HQ', 'Headquarters'), ('BRANCH', 'Branch')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HQ_ADMIN', 'HQ Administrator'), ('BRANCH_ADMIN', 'Branch Administrator'), ('DENTIST', 'Dentist'), ('ASSISTANT', 'Dental Assistant'), ('FRONT_DESK', 'Front Desk'), ('READ_ONLY', 'Read Only'), ('EXTERNAL_GUEST', 'External Guest')], max_length=20)),
                ('professional_type', models.CharField(choices=[('DDS', 'Doctor of Dental Surgery'), ('DMD', 'Doctor of Medicine in Dentistry'), ('RDH', 'Registered Dental Hygienist'), ('RDA', 'Registered Dental Assistant'), ('ADMIN', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
