# Generated by Django 5.0.1 on 2025-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='is_dicom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.FileField(upload_to='cases/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image_type',
            field=models.CharField(choices=[('PHOTO', 'Photograph'), ('XRAY', 'X-Ray'), ('CBCT', 'CBCT Scan'), ('MRI', 'MRI'), ('CT', 'CT Scan'), ('DICOM', 'DICOM'), ('DIAGRAM', 'Diagram'), ('OTHER', 'Other')], default='PHOTO', max_length=20),
        ),
    ]
