# Generated by Django 5.0.1 on 2025-08-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseimage_is_dicom_alter_caseimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Sort order for DICOM series'),
        ),
    ]
