# Generated by Django 5.0.1 on 2025-08-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseimage',
            options={'ordering': ['case', 'order']},
        ),
    ]
