# Generated by Django 5.0.1 on 2025-08-27 02:14

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_caseimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.FileField(upload_to=cases.models.case_image_upload_path),
        ),
    ]
