# Generated by Django 5.0.1 on 2025-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_caseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(help_text='Chart Number', max_length=50, unique=True),
        ),
    ]
