# Generated by Django 5.0.1 on 2025-08-29 18:11

import cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_category_alter_case_clinical_findings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='is_dicom',
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image_type',
            field=models.CharField(choices=[('PHOTO', 'Photograph'), ('PANO', 'Panoramic X-Ray'), ('CBCT', 'CBCT Scan'), ('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT Scan'), ('DICOM', 'DICOM'), ('DIAGRAM', 'Diagram'), ('OTHER', 'Other')], default='PHOTO', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=cases.models.case_image_upload_path)),
                ('is_dicom', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0, help_text='Sort order for DICOM series')),
                ('caseimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cases.caseimage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
