# Generated by Django 5.0.1 on 2025-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_caseimage_options_remove_caseimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='is_deidentified',
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='taken_date',
        ),
        migrations.AddField(
            model_name='caseimageitem',
            name='image_type',
            field=models.CharField(choices=[('PHOTO', 'Photograph'), ('PANO', 'Panoramic X-Ray'), ('CBCT', 'CBCT Scan'), ('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT Scan'), ('DICOM', 'DICOM'), ('DIAGRAM', 'Diagram'), ('PDF', 'PDF Document'), ('ZIP', 'ZIP Archive'), ('OTHER', 'Other')], default='PHOTO', max_length=20),
        ),
        migrations.AddField(
            model_name='caseimageitem',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this upload batch'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='title',
            field=models.CharField(help_text='Name of this upload batch', max_length=200),
        ),
        migrations.AlterField(
            model_name='caseimageitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Sort order within the batch'),
        ),
    ]
