# Generated by Django 5.0.1 on 2025-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_title_caseopinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseimageitem',
            name='image_type',
            field=models.CharField(choices=[('PHOTO', 'Photograph'), ('PANO', 'Panoramic'), ('CBCT', 'CBCT'), ('IOXray', 'Intraoral X-Ray'), ('3DScan', '3D Scan'), ('PDF', 'PDF Document'), ('ZIP', 'ZIP Archive'), ('OTHER', 'Other')], default='PHOTO', max_length=20),
        ),
    ]
