# Generated by Django 5.0.1 on 2025-09-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_caseimageitem_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
